#!/bin/bash -l
#SBATCH --time=3:00:00
#SBATCH -A john2185
#SBATCH -n 10
#SBATCH --output=/depot/john2185/data/ellis123/PM_blast_sequences/task01.out
#SBATCH --error=/depot/john2185/data/ellis123/PM_blast_sequences/task01.error.out
#SBATCH --job-name task01

cp ../../PM_BlastSequences/*blast-output.txt .

touch PM-gyrB.fa

for i in *blast-output.txt;
  do echo ">"$i >> PM-gyrB.fa;
  grep "gyrB" $i | cut -f 13 >> PM-gyrB.fa;
done

echo "End Time"
date +"%d %B %Y %H:%M:%S"
